Repository opendatahub-io/odh-manifests, pull requests merged in 2020-05, with the labels that each got.

#53 Initial set of basic tests for odh
  tests/Dockerfile
  tests/README.md
  tests/basictests/ailibrary.sh
  tests/basictests/airflow.sh
  tests/basictests/grafana.sh
  tests/basictests/jupyterhub.sh
  tests/basictests/kafka.sh
  tests/basictests/odhargo.sh
  tests/basictests/prometheus.sh
  tests/basictests/superset.sh
  tests/resources/ai_library_cr.yaml
  tests/resources/kfctl_openshift.yaml
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/util
Labels: approved, ¯\_(ツ)_/¯

#55 Fixing permissions in /kfdef dir in test image
  tests/Dockerfile
Labels: approved

#56 Adding some debug info for ci system runs and making kubeconfig writable
  tests/scripts/installandtest.sh
Labels: approved

#57 Changes for kubeconfig
  tests/Dockerfile
  tests/scripts/installandtest.sh
Labels: approved

#58 Change kfdef to use apiVersion kfdef.apps.kubeflow.org/v1
  kfdef/kfctl_openshift.yaml
Labels: approved, lgtm

#75 Increase sleep after install before tests
  tests/scripts/install.sh
Labels: approved

#76 Fixing up manifests in kfctl_openshift.yaml to point at PR sha
  tests/scripts/install.sh
Labels: approved

#59 Setting ai library operator image version to tag v0.6
  ai-library/operator/base/kustomization.yaml
  tests/basictests/ailibrary.sh
Labels: approved, lgtm, ¯\_(ツ)_/¯

#77 applying PR patch to master to get proper manifests for test run
  tests/Dockerfile
  tests/scripts/install.sh
Labels: approved

#52 Adding certified Seldon Operator
  kfdef/kfctl_openshift.yaml
  odhseldon/README.md
  odhseldon/cluster/base/kustomization.yaml
  odhseldon/cluster/base/subscription.yaml
Labels: approved, lgtm

#83 Adding README to Superset component
  superset/README.md
Labels: approved, lgtm

#82 Add readme for spark operator
  README.md
  radanalyticsio/README.md
Labels: approved, lgtm

#87 Updating kfdef for testing and increasing settle time before testing
  tests/basictests/jupyterhub.sh
  tests/resources/kfctl_openshift.yaml
  tests/scripts/install.sh
Labels: approved, do-not-merge/hold

#54 Adding README for AI Library
  README.md
  ai-library/README.md
Labels: approved, lgtm

#81 Adding README for grafana component
  grafana/README.md
Labels: approved, lgtm

#85 Adding README for kafka component
  kafka/README.md
Labels: approved, lgtm

#78 Adding document talking about tests for this repo
  tests/TESTING.md
Labels: approved, lgtm

#90 Restoring jupyterhub tests
  tests/basictests/jupyterhub.sh
Labels: approved, ci/cd, lgtm

#102 Update JupyterHub image to 3.0.7-e36ea98
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
Labels: approved, lgtm

#101 Add Makefile for releases
  Makefile
  RELEASE.md
Labels: approved, lgtm
