Repository opendatahub-io/odh-manifests, pull requests merged in 2020-12, with the labels that each got.

#256 Updating URL to oc (mirror has removed the "latest" link)
  tests/Dockerfile
Labels: approved, lgtm

#250 feat(ceph): Export ceph credentials into a secret
  ceph/README.md
  ceph/object-storage/nano/base/kustomization.yaml
  ceph/object-storage/nano/base/secret-rbac.yaml
  ceph/object-storage/nano/base/statefulset.yaml
Labels: approved, lgtm, needs-ok-to-test, ok-to-test

#260 Include new option to skip operator install for use when operator is already installed
  tests/scripts/install.sh
Labels: approved, lgtm

#261 Make $HOME writable so that openshift-ci can do its thing as needed
  tests/Dockerfile
Labels: approved, lgtm

#224 add Architectural Decision Record: Release Policy
  docs/adr/0000-odh-release-policy.md
  docs/adr/README.md
  docs/adr/template.md
Labels: approved, lgtm

#262 Gracefully handle if log grabbing fails due to operator being in another project (when using test image in operator repo)
  tests/scripts/installandtest.sh
Labels: approved

#263 Removing misleading stderr output and including some helpful information when installing the operator
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
Labels: approved

#267 Checking for test success before saving our logs
  tests/scripts/installandtest.sh
Labels: approved

#268 Update odh-dashboard deployment imagePullPolicy to "Always"
  odh-dashboard/base/deployment.yaml
Labels: approved, lgtm

#227 feat(data-catalog): Adding Hue
  hue/README.md
  hue/hue/base/hive-site-xml-secret.yaml
  hue/hue/base/hue-ini-secret.yaml
  hue/hue/base/hue-mysql-pvc.yaml
  hue/hue/base/hue-mysql-secret.yaml
  hue/hue/base/hue-mysql-service.yaml
  hue/hue/base/hue-mysql.yaml
  hue/hue/base/hue-mysqld-exporter-secret.yaml
  hue/hue/base/hue-route.yaml
  hue/hue/base/hue-sample-s3-secret.yaml
  hue/hue/base/hue-service.yaml
  hue/hue/base/hue.yaml
  hue/hue/base/kustomization.yaml
  hue/hue/base/params.env
  hue/hue/base/params.yaml
  hue/hue/overlays/storage-class/kustomization.yaml
  hue/hue/overlays/storage-class/pvc-patch.yaml
  tests/basictests/hue.sh
  tests/setup/kfctl_openshift.yaml
Labels: approved, lgtm, ok-to-test
