Repository opendatahub-io/odh-manifests, pull requests merged in 2020-08, with the labels that each got.

#163 BUGFIX: Update grafana operator v2.0.0 channel to original
  grafana/cluster/base/subscription.yaml
Labels: approved, lgtm

#165 Update kf-manifest ref to v1.0-branch-openshift
  kfdef/kfctl_openshift.yaml
Labels: approved, lgtm

#160 Mixing ODH Prometheus and Grafana with Kubeflow
  kfdef/kfctl_openshift_kubeflow_monitoring.yaml
  prometheus/operator/overlays/kubeflow/kubeflow-servicemonitor.yaml
  prometheus/operator/overlays/kubeflow/kustomization.yaml
Labels: approved, lgtm

#162 Switch to notebook images built by Thoth and add tests for each of them
  jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/additional/scipy-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/additional/tensorflow-notebook-imagestream.yaml
  tests/Dockerfile
  tests/Makefile
  tests/basictests/jupyterhub.sh
  tests/basictests/jupyterhub/jhtest.py
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/util
Labels: approved, lgtm

#155 Adding documentation for running containerized tests
  tests/README.md
Labels: approved, lgtm

#176 Update Chrome and Chromedriver
  tests/Dockerfile
Labels: approved

#171 Add Elyra to list of notebooks available for ODH
  .gitignore
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/additional/kustomization.yaml
  jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/kustomization.yaml
Labels: lgtm, ok-to-test

#173 Adding Argo Grafana Dashboard
  grafana/grafana/base/argo-dashboard.yaml
  grafana/grafana/base/kustomization.yaml
Labels: approved, lgtm

#172 Add Kafka integration tests
  tests/Pipfile.lock
  tests/basictests/kafka.sh
  tests/resources/kafka-test.job.yaml
  tests/resources/kafka/Makefile
  tests/resources/kafka/image/app.sh
  tests/resources/kafka/image/consumer/consumer.py
  tests/resources/kafka/image/producer/producer.py
  tests/resources/kafka/image/requirements.txt
Labels: approved, lgtm
