Repository opendatahub-io/odh-manifests, pull requests merged in 2020-06, with the labels that each got.

#108 Changes to use the opendatahub-operator instead of kfctl.
  tests/Dockerfile
  tests/README.md
  tests/kubeconfig
  tests/resources/operatorsetup
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#109 Revert "Changes to use the opendatahub-operator instead of kfctl."
  tests/Dockerfile
  tests/README.md
  tests/kubeconfig
  tests/resources/operatorsetup
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
Labels: approved

#110 Change to tests that install ODH via the opendatahub-operator
  .gitignore
  tests/Dockerfile
  tests/README.md
  tests/resources/operatorsetup
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#116 Update Manager to delete empty namespace creation
  airflow/operator/manager/manager.yaml
Labels: approved, lgtm

#118 Adding functionality tests for ai library.
  tests/Dockerfile
  tests/functionalitytests/ailibraryfun.sh
  tests/resources/ai_library_cr.yaml
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#134 Converting tests to use try_until with a default timeout of 20 minutes
  tests/Dockerfile
  tests/basictests/ailibrary.sh
  tests/basictests/airflow.sh
  tests/basictests/grafana.sh
  tests/basictests/jupyterhub.sh
  tests/basictests/kafka.sh
  tests/basictests/odhargo.sh
  tests/basictests/prometheus.sh
  tests/basictests/superset.sh
  tests/functionalitytests/ailibraryfun.sh
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/setup/kfctl_openshift.yaml
  tests/setup/operatorsetup
  tests/util
Labels: approved, lgtm

#138 Fix typo for odhdefaultinterval in ailibrary test
  tests/basictests/ailibrary.sh
Labels: approved, lgtm

#137 Fixed to subscribe to latest seldon operator 1.2
  odhseldon/cluster/base/subscription.yaml
Labels: approved, lgtm

#131 Add tests for Radanalytics spark-operator
  tests/basictests/radanalytics.sh
  tests/resources/radanalytics.sparkapplication.yaml
  tests/resources/radanalytics.sparkcluster.yaml
Labels: approved, ci/cd, lgtm

#130 Adding tests for prometheus
  tests/basictests/prometheus.sh
Labels: approved, lgtm

#129 Additional tests for grafana functionality
  tests/Dockerfile
  tests/basictests/grafana.sh
Labels: approved, lgtm

#124 odh-argo testing Adding an example workflow test for argo
  tests/basictests/odhargo.sh
  tests/resources/argo-hello-world.yaml
Labels: approved, lgtm

#127 Adding basic test for seldon
  tests/basictests/seldon.sh
  tests/resources/seldon-model.json
Labels: approved, lgtm

#139 Re-enabling AI library functionality test after Seldon upgrade
  tests/basictests/ailibrary.sh
Labels: approved, lgtm

#140 Functionality tests for Airflow
  tests/basictests/airflow.sh
  tests/resources/airflowbase.yaml
  tests/resources/airflowcluster.yaml
Labels: approved, lgtm
