Repository opendatahub-io/odh-manifests, pull requests merged in 2020-11, with the labels that each got.

#219 Use Postgres image from registry.rh.io to avoid breakage when OpenShift removes older versions
  jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml
Labels: approved, lgtm

#226 Pinning strimzi operator subscription to strimzi-0.19.x channel
  kafka/cluster/base/subscription.yaml
Labels: approved

#213 Update Grafana Operator Version
  grafana/cluster/base/subscription.yaml
  grafana/grafana/base/grafana.yaml
Labels: approved, lgtm

#230 Fix Kafka Monitoring
  prometheus/operator/base/kafka-podmonitors.yaml
  prometheus/operator/base/kafka-servicemonitor.yaml
  prometheus/operator/base/kustomization.yaml
  prometheus/operator/base/prometheus.yaml
Labels: approved, lgtm

#239 Add Prometheus servicemonitor for Jupyterhub service
  prometheus/operator/base/jupyterhub-servicemonitor.yaml
  prometheus/operator/base/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#207 Bump elyra image up to v0.0.5
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
Labels: approved, lgtm, ok-to-test

#241 Adding debug info and sleep to let test cluster settle before running the test suite
  airflow/example-celery/base/base.yaml
  tests/basictests/airflow.sh
  tests/resources/airflowbase.yaml
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#240 Add Ceph nano for minimal object storage
  ceph/README.md
  ceph/object-storage/nano/base/kustomization.yaml
  ceph/object-storage/nano/base/service-account.yaml
  ceph/object-storage/nano/base/service.yaml
  ceph/object-storage/nano/base/statefulset.yaml
  ceph/object-storage/scc/base/kustomization.yaml
  ceph/object-storage/scc/base/params.env
  ceph/object-storage/scc/base/params.yaml
  ceph/object-storage/scc/base/securitycontextconstraint.yaml
Labels: approved, lgtm

#246 Updating google-chrome-stable package name; using dnf instead of yum.
  tests/Dockerfile
Labels: approved, lgtm

#243 Use thoth-station repositories in cuda build process
  jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml
  jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml
Labels: approved, lgtm

#244 Add hyperlinks to README.md in subdirectories
  README.md
Labels: approved, lgtm, ok-to-test

#215 Add support for ARTIFACT_DIR in CI tests
  .gitignore
  tests/Makefile
  tests/README.md
  tests/basictests/jupyterhub/jhtest.py
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
Labels: approved, lgtm
