Repository opendatahub-io/odh-manifests, pull requests merged in 2021-04, with the labels that each got.

#362 Use secret param in JH DB for postgres pass
  jupyterhub/README.md
  jupyterhub/jupyterhub/base/jupyterhub-db-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-secret.yaml
  jupyterhub/jupyterhub/base/params.yaml
Labels: approved, lgtm

#381 Add generic data science notebook to JH deployment
  jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/additional/kustomization.yaml
  jupyterhub/notebook-images/overlays/build/generic-data-science-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/kustomization.yaml
  tests/basictests/jupyterhub.sh
Labels: approved, lgtm

#368 include new ubi8 cuda-11.0.3 supporting python3.8 notebooks
  jupyterhub/README.md
  jupyterhub/notebook-images/overlays/cuda-11.0.3/README.md
  jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-ubi8-build-chain.yaml
  jupyterhub/notebook-images/overlays/cuda-11.0.3/gpu-notebook.yaml
  jupyterhub/notebook-images/overlays/cuda-11.0.3/kustomization.yaml
  jupyterhub/notebook-images/overlays/cuda-11.0.3/params.env
  jupyterhub/notebook-images/overlays/cuda-11.0.3/params.yaml
Labels: approved, lgtm

#337 Add OpenShift Pipelines component
  openshift-pipelines/README.md
  openshift-pipelines/cluster/base/kustomization.yaml
  openshift-pipelines/cluster/base/subscription.yaml
  tests/basictests/openshift-pipelines.sh
  tests/resources/openshift-pipelines/pipeline-hello-world.yaml
  tests/resources/openshift-pipelines/pipelinerun-hello-world.yaml
  tests/resources/openshift-pipelines/task-hello-world.yaml
  tests/setup/kfctl_openshift.yaml
Labels: approved, enhancement, lgtm

#383 add connects-to annotation from jupyterhub to jupyterhub-db
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
Labels: approved, lgtm, ok-to-test

#389 trim the gpu image names for proper image-pull
  jupyterhub/notebook-images/overlays/cuda-11.0.3/gpu-notebook.yaml
Labels: approved, lgtm

#384 configure buildconfig ref based on tags for stability
  jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/minimal-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/scipy-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/spark-minimal-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/spark-scipy-notebook-buildconfig.yaml
  jupyterhub/notebook-images/overlays/build/tensorflow-notebook-buildconfig.yaml
Labels: approved, lgtm

#316 Add JupyterHub dashboards
  grafana/grafana/base/dashboards/jupyterhub-sli-slo.json
  grafana/grafana/base/dashboards/jupyterhub-usage.json
  grafana/grafana/base/jupyterhub-sli-dashboard.yaml
  grafana/grafana/base/jupyterhub-usage-dashboard.yaml
  grafana/grafana/base/kustomization.yaml
  prometheus/operator/base/cluster-metrics-servicemonitor.yaml
  prometheus/operator/base/cluster-monitoring-role-binding.yaml
  prometheus/operator/base/cluster-monitoring-role.yaml
  prometheus/operator/base/kustomization.yaml
  prometheus/operator/base/secrets/kustomization.yaml
  prometheus/operator/base/secrets/prometheus-k8s.yaml
Labels: approved, lgtm, ok-to-test

#380 Update s2i-lab-elyra notebook image to v0.0.7
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
Labels: approved, lgtm, ok-to-test

#392 Update JH image to fix GPU setting and CI issue
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
Labels: approved, lgtm

#390 annotation set with image name and python dependency details
  jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml
Labels: approved, lgtm

#393 Adding docs for the SKIP_OPERATOR_INSTALL env var in tests
  tests/README.md
Labels: approved, lgtm

#398 Split the JSP configmap into profiles and sizes
  jupyterhub/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
  jupyterhub/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
Labels: approved, lgtm

#402 Update OpenShift Pipelines starting version to v1.3.1
  openshift-pipelines/cluster/base/subscription.yaml
Labels: approved, lgtm

#406 Update JupyterHub to v0.2.8
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
  jupyterhub/jupyterhub/base/jupyterhub-nodereader-rolebinding.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
  jupyterhub/jupyterhub/base/params.yaml
Labels: approved, lgtm

#400 Dashboard refactor
  grafana/grafana/base/argo-dashboards/argo-dashboard.yaml
  grafana/grafana/base/argo-dashboards/kustomization.yaml
  grafana/grafana/base/jupyterhub-dashboards/jupyterhub-sli-dashboard.yaml
  grafana/grafana/base/jupyterhub-dashboards/jupyterhub-sli-slo.json
  grafana/grafana/base/jupyterhub-dashboards/jupyterhub-usage-dashboard.yaml
  grafana/grafana/base/jupyterhub-dashboards/jupyterhub-usage.json
  grafana/grafana/base/jupyterhub-dashboards/kustomization.yaml
  grafana/grafana/base/kafka-dashboards/kafka-dashboard.yaml
  grafana/grafana/base/kafka-dashboards/kustomization.yaml
  grafana/grafana/base/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#405 Update Kafka Operator Subscription to v0.22.x
  kafka/cluster/base/subscription.yaml
  kafka/kafka/base/kafka-cluster.yaml
  kafka/kafka/base/kafka-metrics-config.yaml
  kafka/kafka/base/kustomization.yaml
Labels: approved, lgtm

#408 Image details set in annotation for gpu images
  jupyterhub/notebook-images/overlays/cuda-11.0.3/gpu-notebook.yaml
Labels: approved, lgtm

#403 Add archive of pods & events during CI runs
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#373 Add Trino kustomize manifests
  README.md
  tests/basictests/trino.sh
  tests/setup/kfctl_openshift.yaml
  trino/README.md
  trino/base/aws-secret.yaml
  trino/base/hadoop-config.yaml
  trino/base/hive-config.yaml
  trino/base/hive-db-secret.yaml
  trino/base/hive-jmx-config.yaml
  trino/base/hive-metastore-dc.yaml
  trino/base/hive-metastore-entrypoint.yaml
  trino/base/hive-metastore-service.yaml
  trino/base/kustomization.yaml
  trino/base/params.env
  trino/base/params.yaml
  trino/base/trino-catalog-secret.yaml
  trino/base/trino-config-secret.yaml
  trino/base/trino-coordinator-dc.yaml
  trino/base/trino-db-dc.yaml
  trino/base/trino-db-pvc.yaml
  trino/base/trino-db-secret.yaml
  trino/base/trino-db-service.yaml
  trino/base/trino-route.yaml
  trino/base/trino-service.yaml
  trino/base/trino-worker-dc.yaml
  trino/overlays/storage-class/kustomization.yaml
  trino/overlays/storage-class/pvc-patch.yaml
Labels: approved, lgtm

#419 Update elyra notebook image to v0.0.8
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
Labels: approved, lgtm, ok-to-test
