Repository opendatahub-io/odh-manifests, pull requests merged in 2021-03, with the labels that each got.

#329 Remove tls-acme annotation from JuptyerHub route
  jupyterhub/jupyterhub/base/jupyterhub-route.yaml
Labels: approved, lgtm

#330 [JupyterHub] Fix auth for prometheus /metrics endpoint behind auth proxy
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-secret.yaml
  prometheus/operator/base/servicemonitor.yaml
Labels: approved, lgtm, ok-to-test

#338 Update Grafana Operator Version to 3.9.0
  grafana/cluster/base/subscription.yaml
Labels: approved, lgtm, ok-to-test

#339 Update JH image with prometheus authentication
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
Labels: approved, lgtm

#342 Add JH groups configuration CM
  jupyterhub/README.md
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-groups-configmap.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
  jupyterhub/jupyterhub/base/params.env
  jupyterhub/jupyterhub/base/params.yaml
Labels: approved, lgtm

#345 Update Jupyterhub image to v0.2.2
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
Labels: approved, lgtm

#348 Remove empty odh operator log artifact from tests runs
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#334 Added ImageChange trigger to the JupyterHub deployment config
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
Labels: approved, lgtm

#297 Update Elyra image to v2.0.1
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
Labels: approved, lgtm, ok-to-test

#351 Add env vars to JH so that we don't lose auth_state on restart
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
  jupyterhub/jupyterhub/base/jupyterhub-secret.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
  jupyterhub/jupyterhub/base/params.env
  jupyterhub/jupyterhub/base/params.yaml
  tests/basictests/jupyterhub/jhtest.py
Labels: approved, lgtm

#350 Add oauth proxy to ODH dashboard
  odh-dashboard/README.md
  odh-dashboard/base/deployment.yaml
  odh-dashboard/overlays/authentication/clusterrolebinding.yaml
  odh-dashboard/overlays/authentication/deployment.yaml
  odh-dashboard/overlays/authentication/kustomization.yaml
  odh-dashboard/overlays/authentication/route.yaml
  odh-dashboard/overlays/authentication/service-account.yaml
  odh-dashboard/overlays/authentication/service.yaml
Labels: approved, lgtm

#354 Argo Workflows instead of Argo
  README.md
Labels: approved, lgtm, needs-ok-to-test, ok-to-test

#360 Move the JH DeploymentConfig imageChange trigger to an overlay
  jupyterhub/README.md
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/overlays/trigger-imagechange/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/overlays/trigger-imagechange/kustomization.yaml
Labels: approved, lgtm

#349 Update Metrics endpoints for ODH operator
  prometheus/operator/base/kustomization.yaml
  prometheus/operator/base/params.yaml
  prometheus/operator/base/prometheus-monitoring-role-binding.yaml
  prometheus/operator/base/prometheus-monitoring-role.yaml
  prometheus/operator/base/prometheus.yaml
  prometheus/operator/base/service-monitors/application-service-monitor.yaml
  prometheus/operator/base/service-monitors/kustomization.yaml
  prometheus/operator/base/service-monitors/operator-service-monitor.yaml
  tests/basictests/prometheus.sh
Labels: approved, lgtm

#367 point to tag reference instead of master branch
  jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml
Labels: approved, lgtm

#361 Update JSP to 0.2.2, add secrets to the role
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
  jupyterhub/jupyterhub/base/jupyterhub-role.yaml
  tests/basictests/jupyterhub.sh
  tests/basictests/jupyterhub/jhtest.py
Labels: approved, lgtm
