Repository opendatahub-io/odh-manifests, pull requests merged in 2021-06, with the labels that each got.

#429 Redeploy all core pods upon image update
  jupyterhub/README.md
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
  jupyterhub/jupyterhub/overlays/build/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/overlays/build/jupyterhub-img-imagestream.yaml
  jupyterhub/jupyterhub/overlays/build/kustomization.yaml
  jupyterhub/jupyterhub/overlays/trigger-imagechange/jupyterhub-dc.yaml
  jupyterhub/jupyterhub/overlays/trigger-imagechange/kustomization.yaml
Labels: approved, lgtm

#435 Update JupyterHub to v0.3.0 with new spawner UI and bump s2i-generic-notebook to v0.0.3
  jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
  jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml
  tests/Dockerfile
  tests/basictests/jupyterhub.sh
  tests/basictests/jupyterhub/jhtest.py
  tests/resources/ods-ci/test-odh-jupyterlab-notebook.robot
  tests/resources/ods-ci/test-variables.yml
Labels: approved, lgtm

#437 support for pre-commit and python-editor
  jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml
Labels: approved, lgtm

#438 switch to rhods based base repo for cuda builds
  jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-ubi8-build-chain.yaml
Labels: approved, lgtm

#439 Change Trino Route to a secured one
  trino/README.md
  trino/base/trino-route.yaml
Labels: approved, lgtm

#440 Add builds and buildconfigs read permissions to odh-dashboard role
  odh-dashboard/base/role.yaml
Labels: approved, lgtm, ok-to-test

#445 Fix missing names in additional image streams
  jupyterhub/notebook-images/base/spark-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/additional/spark-scipy-notebook-imagestream.yaml
Labels: approved, lgtm, needs-ok-to-test, ok-to-test

#444 Add permission to JH SA to get build info
  jupyterhub/jupyterhub/base/jupyterhub-role.yaml
Labels: approved, lgtm

#443 Update JupyterHub base image source to v3.5.3
  jupyterhub/jupyterhub/overlays/build/jupyterhub-buildconfig.yaml
Labels: approved, lgtm

#446 Add a general cluster role to JH
  jupyterhub/jupyterhub/base/jupyterhub-cluster-role.yaml
  jupyterhub/jupyterhub/base/jupyterhub-cluster-rolebinding.yaml
  jupyterhub/jupyterhub/base/jupyterhub-nodereader-rolebinding.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
Labels: approved, lgtm

#449 Fix and organize Hive Metastore descriptors from Trino
  trino/base/hadoop-config.yaml
  trino/base/hive-config.yaml
  trino/base/hive-metastore-entrypoint.yaml
Labels: approved, lgtm
