Repository opendatahub-io/odh-manifests, pull requests merged in 2021-01, with the labels that each got.

#228 feat(data-catalog): Adding Thriftserver
  tests/basictests/thriftserver.sh
  tests/setup/kfctl_openshift.yaml
  thriftserver/README.md
  thriftserver/thriftserver/base/kustomization.yaml
  thriftserver/thriftserver/base/params.env
  thriftserver/thriftserver/base/params.yaml
  thriftserver/thriftserver/base/thriftserver-db-exporter.yaml
  thriftserver/thriftserver/base/thriftserver-db-pvc.yaml
  thriftserver/thriftserver/base/thriftserver-db-secret.yaml
  thriftserver/thriftserver/base/thriftserver-db-service.yaml
  thriftserver/thriftserver/base/thriftserver-db.yaml
  thriftserver/thriftserver/base/thriftserver-hdfs-hive-secret.yaml
  thriftserver/thriftserver/base/thriftserver-pvc.yaml
  thriftserver/thriftserver/base/thriftserver-route.yaml
  thriftserver/thriftserver/base/thriftserver-sample-s3-secret.yaml
  thriftserver/thriftserver/base/thriftserver-server-conf-secret.yaml
  thriftserver/thriftserver/base/thriftserver-service.yaml
  thriftserver/thriftserver/base/thriftserver.yaml
  thriftserver/thriftserver/overlays/create-spark-cluster/kustomization.yaml
  thriftserver/thriftserver/overlays/create-spark-cluster/params.yaml
  thriftserver/thriftserver/overlays/create-spark-cluster/spark-cluster.yaml
  thriftserver/thriftserver/overlays/create-spark-cluster/thriftserver-config-patch.yaml
  thriftserver/thriftserver/overlays/storage-class/kustomization.yaml
  thriftserver/thriftserver/overlays/storage-class/pvc-patch.yaml
Labels: approved, lgtm, ok-to-test

#277 disable build-check for odh-manifest
  .aicoe-ci.yaml
Labels: approved, lgtm

#245 Modified jhtest.py and updated jupyterhub-odh image
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
  tests/basictests/jupyterhub/jhtest.py
Labels: approved, lgtm

#271 [Monitoring] Replace jupyterhub servicemonitor with one servicemonitor for odh components
  prometheus/operator/base/jupyterhub-servicemonitor.yaml
  prometheus/operator/base/kustomization.yaml
  prometheus/operator/base/servicemonitor.yaml
Labels: approved, lgtm, ok-to-test

#272 Kafka dashboard: migrate singlestat to new stat panel
  grafana/grafana/base/dashboard.yaml
Labels: approved, lgtm

#283 Increased wait time when running notebooks in JH test
  tests/basictests/jupyterhub/jhtest.py
Labels: approved, lgtm

#286 Update Chromedriver version to 88.0.4324.27
  tests/Dockerfile
Labels: approved, lgtm

#284 Update ODH Dashboard for 1.0 image. Reduce deployment resources.
  odh-dashboard/base/deployment.yaml
Labels: approved, lgtm

#208 Update odhargo component to v2.12.5
  odhargo/README.md
  odhargo/cluster/base/cluster-roles.yaml
  odhargo/cluster/base/crds.yaml
  odhargo/cluster/base/cronworkflow-crd.yaml
  odhargo/cluster/base/kustomization.yaml
  odhargo/cluster/base/workflow-crd.yaml
  odhargo/cluster/base/workflowtmp-crd.yaml
  odhargo/odhargo/base/argo-role.yaml
  odhargo/odhargo/base/argo-rolebinding.yaml
  odhargo/odhargo/base/argo-server-binding.yaml
  odhargo/odhargo/base/argo-server-role.yaml
  odhargo/odhargo/base/argo-server-route.yaml
  odhargo/odhargo/base/argo-workflow-rbac.yaml
  odhargo/odhargo/base/deployment-argo-server.yaml
  odhargo/odhargo/base/deployment-workflow-controller.yaml
  odhargo/odhargo/base/kustomization.yaml
  odhargo/odhargo/base/namespace-install.yaml
  odhargo/odhargo/base/sa-argo-server.yaml
  odhargo/odhargo/base/sa-argo.yaml
  odhargo/odhargo/base/service-argo-server.yaml
  odhargo/odhargo/base/service-workflow-controller.yaml
  odhargo/odhargo/base/test-workflow.yaml
  odhargo/odhargo/base/workflow-configmap.yaml
  odhargo/odhargo/base/workflow-controller-configmap.yaml
  odhargo/odhargo/base/workflow-controller-metrics-route.yaml
  tests/resources/argo-hello-world.yaml
Labels: approved, enhancement, lgtm, ok-to-test

#264 build tensorflow-gpu with cuda and minimal-notebook
  jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml
Labels: approved, lgtm

#291 Fix tf gpu build param
  jupyterhub/notebook-images/overlays/cuda/params.yaml
Labels: approved, lgtm

#296 Updated jupyterhub imagestream image to 0.1.5
  jupyterhub/jupyterhub/base/jupyterhub-img-imagestream.yaml
Labels: approved, lgtm
