Repository opendatahub-io/odh-manifests, pull requests merged in 2022-03, with the labels that each got.

#516 Pachyderm integration
  odhpachyderm/README.md
  odhpachyderm/deployer/base/job.yaml
  odhpachyderm/deployer/base/kustomization.yaml
  odhpachyderm/deployer/base/params.env
  odhpachyderm/deployer/base/params.yaml
  odhpachyderm/deployer/base/role-binding.yaml
  odhpachyderm/deployer/base/role.yaml
  odhpachyderm/deployer/base/service-account.yaml
  odhpachyderm/deployer/base/test_job_script.sh
  odhpachyderm/operator/base/kustomization.yaml
  odhpachyderm/operator/base/params.env
  odhpachyderm/operator/base/params.yaml
  odhpachyderm/operator/base/subscription.yaml
  tests/basictests/pachyderm.sh
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#532 add pachyderm as a new components in the README
  README.md
Labels: lgtm, approved, needs-ok-to-test, ok-to-test

#533 Add groups-config configmap
  jupyterhub/jupyterhub/base/groups-config.yaml
  jupyterhub/jupyterhub/base/kustomization.yaml
  jupyterhub/jupyterhub/base/params.yaml
Labels: lgtm, approved

#534 Add rbac to deployment config
  odh-dashboard/base/role.yaml
Labels: lgtm

#535 Update dashboard rbac
  odh-dashboard/base/cluster-role-binding.yaml
  odh-dashboard/base/cluster-role.yaml
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/base/role.yaml
Labels: lgtm, approved

#536 Remove duplicate role objects
  odh-dashboard/base/role.yaml
Labels: lgtm, approved

#505 Update Grafana operator to work on OCP 4.9
  grafana/cluster/base/subscription.yaml
  grafana/grafana/base/argo-dashboards/argo-dashboard.yaml
  grafana/grafana/base/grafana.yaml
  prometheus/operator/base/service-monitors/application-service-monitor.yaml
  tests/basictests/airflow.sh
  tests/basictests/grafana.sh
Labels: lgtm, approved

#539 Update Superset OAuth role code to account for nonexistent Role
  superset/base/superset_config.py
Labels: lgtm, approved

#547 Update chromedriver to 100.0.4896.60
  tests/Dockerfile
Labels: approved

#548 Pin ods-ci repo to use 1.7.0-5 branch
  tests/Dockerfile
Labels: lgtm, approved

#544 Upgrade superset to 1.4.1
  superset/base/kustomization.yaml
  superset/base/superset_config.py
Labels: kind/enhancement, lgtm, approved
