Repository opendatahub-io/odh-manifests, pull requests merged in 2022-08, with the labels that each got.

#609 Adding ServiceMonitor to ML Pipelines
  ml-pipelines/base/kustomization.yaml
  ml-pipelines/prometheus/kustomization.yaml
  ml-pipelines/prometheus/monitor.yaml
Labels: lgtm, approved

#615 Update failing tests
  tests/Dockerfile
Labels: lgtm, approved, needs-ok-to-test

#613 Adding a monitoring check to pipeline tests
  tests/basictests/ml-pipelines.sh
  tests/resources/ml-pipelines/enable-uwm.yaml
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#591 Add the oauth proxy in front of kfp ui
  ml-pipelines/overlays/ml-pipeline-ui/deployments/ml-pipeline-ui.yaml
  ml-pipelines/overlays/ml-pipeline-ui/kustomization.yaml
  ml-pipelines/overlays/ml-pipeline-ui/rolebindings/auth-delegator.yaml
  ml-pipelines/overlays/ml-pipeline-ui/routes/ml-pipeline-ui.yaml
  ml-pipelines/overlays/ml-pipeline-ui/serviceaccounts/ml-pipeline-ui.yaml
  ml-pipelines/overlays/ml-pipeline-ui/services/ml-pipeline-ui.yaml
Labels: lgtm, approved

#599 Add overlay for model-mesh serving component
  kfdef/kfctl_model_serving.yaml
  kfdef/kfctl_openshift.yaml
  model-mesh/overlays/odh-model-controller/default/kustomization.yaml
  model-mesh/overlays/odh-model-controller/default/manager_auth_proxy_patch.yaml
  model-mesh/overlays/odh-model-controller/default/manager_config_patch.yaml
  model-mesh/overlays/odh-model-controller/kustomization.yaml
  model-mesh/overlays/odh-model-controller/manager/controller_manager_config.yaml
  model-mesh/overlays/odh-model-controller/manager/kustomization.yaml
  model-mesh/overlays/odh-model-controller/manager/manager.yaml
  model-mesh/overlays/odh-model-controller/manager/servingruntimes_config.yaml
  model-mesh/overlays/odh-model-controller/prometheus/kustomization.yaml
  model-mesh/overlays/odh-model-controller/prometheus/monitor.yaml
  model-mesh/overlays/odh-model-controller/rbac/auth_proxy_client_clusterrole.yaml
  model-mesh/overlays/odh-model-controller/rbac/auth_proxy_role.yaml
  model-mesh/overlays/odh-model-controller/rbac/auth_proxy_role_binding.yaml
  model-mesh/overlays/odh-model-controller/rbac/auth_proxy_service.yaml
  model-mesh/overlays/odh-model-controller/rbac/kustomization.yaml
  model-mesh/overlays/odh-model-controller/rbac/leader_election_role.yaml
  model-mesh/overlays/odh-model-controller/rbac/leader_election_role_binding.yaml
  model-mesh/overlays/odh-model-controller/rbac/role.yaml
  model-mesh/overlays/odh-model-controller/rbac/role_binding.yaml
  model-mesh/overlays/odh-model-controller/rbac/service_account.yaml
  tests/basictests/modelmesh.sh
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#617 Add readme
  ml-pipelines/README.md
Labels: lgtm, approved

#624 Fix test file name
  tests/basictests/ml-pipelines.sh
  tests/resources/ml-pipelines/test-pipeline-run.yaml
Labels: lgtm, approved

#625 Fix pipeline run name
  tests/basictests/ml-pipelines.sh
Labels: lgtm

#623 Update JH Secret metadata
  jupyterhub/jupyterhub/base/jupyterhub-secret.yaml
  jupyterhub/jupyterhub/base/traefik-credentials-secret.yaml
Labels: lgtm, approved

#626 Update test kfdef to properly account for sed
  tests/basictests/ml-pipelines.sh
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#592 Use JH images in notebook controller tests
  jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml
  tests/resources/notebook-controller/notebooks/thoth-generic-oauth-notebook.yaml
  tests/resources/notebook-controller/notebooks/thoth-minimal-notebook.yaml
  tests/resources/notebook-controller/notebooks/thoth-minimal-oauth-notebook.yaml
Labels: lgtm, approved

#633 Fix CI Tests
  kfdef/kfctl_openshift_ml-pipelines.yaml
  ml-pipelines/README.md
  ml-pipelines/base/customresourcedefinitions/scheduledworkflows.yaml
Labels: lgtm, approved

#635 Update README references to master
  ml-pipelines/README.md
Labels: lgtm

#618 Remove .spec.name from GrafanaDashboards
  grafana/grafana/base/argo-dashboards/argo-dashboard.yaml
  grafana/grafana/base/kafka-dashboards/kafka-dashboard.yaml
  grafana/grafana/base/odh-notebook-controller-dashboards/odh-notebook-controller-dashboard.yaml
Labels: lgtm, approved

#630 Model Mesh installation steps
  model-mesh/README.md
Labels: lgtm, approved

#643 Restore OpenShift Pipelines component for use as a dependency
  openshift-pipelines/README.md
  openshift-pipelines/cluster/base/subscription.yaml
  tests/basictests/openshift-pipelines.sh
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#649 Use default OLM channel for ocp pipelines subscription
  openshift-pipelines/cluster/base/subscription.yaml
Labels: lgtm, approved

#652 Adding overlay for minio artifacts
  kfdef/kfctl_openshift_ml-pipelines.yaml
  ml-pipelines/README.md
  ml-pipelines/base/kustomization.yaml
  ml-pipelines/overlays/object-store-minio/deployments/minio.yaml
  ml-pipelines/overlays/object-store-minio/kustomization.yaml
  ml-pipelines/overlays/object-store-minio/persistentvolumeclaims/minio-pvc.yaml
  ml-pipelines/overlays/object-store-minio/secrets/mlpipeline-minio-artifact.yaml
  ml-pipelines/overlays/object-store-minio/services/minio-service.yaml
  tests/setup/kfctl_openshift.yaml
Labels: lgtm, approved

#651 Increase notebook controller memory limits
  odh-notebook-controller/gen_kubeflow_manifests.sh
  odh-notebook-controller/gen_odh_manifests.sh
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/kustomization.yaml
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/manager_openshift_patch.yaml
  odh-notebook-controller/odh-notebook-controller/base/kustomization.yaml
  odh-notebook-controller/odh-notebook-controller/manager/manager.yaml
Labels: lgtm, approved

#656 CI: Change to the rolling channel for operator installs in CI tests
  tests/Dockerfile
  tests/Makefile
  tests/setup/operatorsetup
Labels: lgtm, approved, ci/cd

#660 Add owners file for superset
  superset/OWNERS
Labels: lgtm, approved

#659 Upgrade superset to 1.5.0
  superset/base/kustomization.yaml
Labels: lgtm, approved

#597 Update Elyra notebook image to v0.1.5
  jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
  jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
Labels: lgtm, approved, ok-to-test

#607 Add syntax highlighting to markdown
  RELEASE.md
  ai-library/README.md
  ai-library/tests/README.md
  airflow/README.md
  ceph/README.md
  grafana/README.md
  jupyterhub/README.md
  jupyterhub/notebook-images/overlays/cuda-11.0.3/README.md
  kafka/README.md
  odh-dashboard/README.md
  odhseldon/README.md
  openshift-pipelines/README.md
  prometheus/README.md
  radanalyticsio/README.md
  superset/README.md
  tests/README.md
Labels: lgtm, approved, ok-to-test

#610 Fix tabbing in odh-notebook-controller docs
  odh-notebook-controller/README.md
Labels: lgtm, approved, ok-to-test

#661 Fix ML Pipelines Tests
  tests/basictests/ml-pipelines.sh
Labels: lgtm, approved

#655 Parametrize ML Pipelines deployment
  ml-pipelines/README.md
  ml-pipelines/base/deployments/metadata-grpc-deployment.yaml
  ml-pipelines/base/deployments/metadata-writer.yaml
  ml-pipelines/base/deployments/ml-pipeline-scheduledworkflow.yaml
  ml-pipelines/base/deployments/ml-pipeline.yaml
  ml-pipelines/base/kustomization.yaml
  ml-pipelines/base/params.env
  ml-pipelines/base/params.yaml
  ml-pipelines/overlays/metadata-store-mysql/kustomization.yaml
  ml-pipelines/overlays/metadata-store-postgresql/deployments/postgresql.yaml
  ml-pipelines/overlays/metadata-store-postgresql/kustomization.yaml
  ml-pipelines/overlays/ml-pipeline-ui/deployments/ml-pipeline-ui.yaml
  tests/basictests/ml-pipelines.sh
Labels: lgtm, approved

#664 Add spec.replicas field to 'notebook-controller-deployment'
  odh-notebook-controller/kf-notebook-controller/manager/manager.yaml
Labels: lgtm, approved

#606 Make odh-dashboard cluster role binding unique
  odh-dashboard/base/cluster-role-binding.yaml
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/base/params.yaml
  odh-dashboard/overlays/authentication/clusterrolebinding.yaml
Labels: lgtm, approved, ok-to-test
