Repository opendatahub-io/odh-manifests, pull requests merged in 2022-11, with the labels that each got.

#692 DashboardConfig CRD Changes for 2.4.0
  odh-dashboard/base/odh-dashboard-crd.yaml
Labels: lgtm, approved

#691 Add S3 Override Env Vars for DSP API Server
  data-science-pipelines/base/deployments/ds-pipeline.yaml
  data-science-pipelines/overlays/default-configs/secrets/mlpipeline-minio-artifact.yaml
Labels: lgtm, approved

#699 change apiVersion to rbac.authorization.k8s.io/v1 to support kfctl on ODH 1.4.0 and OCP 4.10
  jupyterhub/jupyterhub/base/jupyterhub-role.yaml
  jupyterhub/jupyterhub/base/jupyterhub-rolebinding.yaml
  jupyterhub/jupyterhub/base/params.yaml
  jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-build-role.yaml
Labels: lgtm, approved, ok-to-test

#701 Remove the protocol from ceph-nano StatefulSet
  ceph/object-storage/nano/base/statefulset.yaml
Labels: approved

#702 Integrate the new prebuild image notebooks into upstream
  notebook-images/base/jupyter-datascience-notebook-imagestream.yaml
  notebook-images/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  notebook-images/base/jupyter-minimal-notebook-imagestream.yaml
  notebook-images/base/jupyter-pytorch-notebook-imagestream.yaml
  notebook-images/base/jupyter-tensorflow-notebook-imagestream.yaml
  notebook-images/base/kustomization.yaml
  tests/resources/notebook-controller/notebooks/cuda-jupyter-minimal-ubi8-python-3-8.yaml
  tests/resources/notebook-controller/notebooks/cuda-jupyter-pytorch-ubi8-python-3-8.yaml
  tests/resources/notebook-controller/notebooks/cuda-jupyter-tensorflow-ubi8-python-3-8.yaml
  tests/resources/notebook-controller/notebooks/jupyter-datascience-ubi8-python-3-8.yaml
  tests/resources/notebook-controller/notebooks/jupyter-minimal-ubi8-python-3-8.yaml
  tests/setup/odh-core.yaml
Labels: lgtm, approved
