Repository opendatahub-io/odh-manifests, pull requests merged in 2023-03, with the labels that each got.

#741 Use test framework to use opendatahub-io/peak repo for testing
  tests/Dockerfile
  tests/README.md
  tests/TESTING.md
Labels: lgtm, approved, ci/cd

#729 Add Data Science Pipelines Operator.
  data-science-pipelines-operator/OWNERS
  data-science-pipelines-operator/README.md
  data-science-pipelines-operator/base/kustomization.yaml
  data-science-pipelines-operator/base/params.env
  data-science-pipelines-operator/base/params.yaml
  data-science-pipelines-operator/configmaps/files/config.yaml
  data-science-pipelines-operator/configmaps/kustomization.yaml
  data-science-pipelines-operator/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  data-science-pipelines-operator/crd/bases/scheduledworkflows.yaml
  data-science-pipelines-operator/crd/bases/viewers.yaml
  data-science-pipelines-operator/crd/external/route.openshift.io_routes.yaml
  data-science-pipelines-operator/crd/kustomization.yaml
  data-science-pipelines-operator/crd/kustomizeconfig.yaml
  data-science-pipelines-operator/manager/kustomization.yaml
  data-science-pipelines-operator/manager/manager-service.yaml
  data-science-pipelines-operator/manager/manager.yaml
  data-science-pipelines-operator/manifests/kustomization.yaml
  data-science-pipelines-operator/prometheus/kustomization.yaml
  data-science-pipelines-operator/prometheus/monitor.yaml
  data-science-pipelines-operator/rbac/kustomization.yaml
  data-science-pipelines-operator/rbac/leader_election_role.yaml
  data-science-pipelines-operator/rbac/leader_election_role_binding.yaml
  data-science-pipelines-operator/rbac/role.yaml
  data-science-pipelines-operator/rbac/role_binding.yaml
  data-science-pipelines-operator/rbac/service_account.yaml
  data-science-pipelines-operator/samples/custom-configs/artifact_script.yaml
  data-science-pipelines-operator/samples/custom-configs/db-creds.yaml
  data-science-pipelines-operator/samples/custom-configs/dspa.yaml
  data-science-pipelines-operator/samples/custom-configs/kustomization.yaml
  data-science-pipelines-operator/samples/custom-configs/storage-creds.yaml
  data-science-pipelines-operator/samples/custom-configs/ui-configmap.yaml
  data-science-pipelines-operator/samples/dspa_all_fields.yaml
  data-science-pipelines-operator/samples/dspa_simple.yaml
  data-science-pipelines-operator/samples/dspa_simple_external_storage.yaml
  data-science-pipelines-operator/samples/kustomization.yaml
  kfdef/kfctl_openshift_ds-pipelines-operator.yaml
  tests/README.md
  tests/basictests/dsp-operator.sh
  tests/resources/dsp-operator/enable-uwm.yaml
  tests/resources/dsp-operator/test-dspo-cr.yaml
  tests/resources/dsp-operator/test-pipeline-run.yaml
  tests/setup/odh-core.yaml
Labels: lgtm, approved

#754 Set version tag v0.1.0 for dsp-operator
  data-science-pipelines-operator/base/kustomization.yaml
  data-science-pipelines-operator/base/params.env
Labels: lgtm, approved

#753 Fix base path in additional overlay for notebook-images
  notebook-images/overlays/additional/kustomization.yaml
Labels: lgtm, approved

#744 Data Science Pipelines auth-delegation crb fix
  data-science-pipelines/overlays/ds-pipeline-ui/kustomization.yaml
  data-science-pipelines/overlays/ds-pipeline-ui/params.yaml
  data-science-pipelines/overlays/ds-pipeline-ui/rolebindings/auth-delegator.yaml
Labels: lgtm, approved, ok-to-test

#761 Sync dspo repo manifests.
  data-science-pipelines-operator/base/kustomization.yaml
  data-science-pipelines-operator/base/params.env
  data-science-pipelines-operator/base/params.yaml
  data-science-pipelines-operator/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  data-science-pipelines-operator/crd/external/monitoring.coreos.com_servicemonitors.yaml
  data-science-pipelines-operator/manager/manager.yaml
  data-science-pipelines-operator/rbac/aggregate_dspa_role.yaml
  data-science-pipelines-operator/rbac/kustomization.yaml
  data-science-pipelines-operator/rbac/role.yaml
  data-science-pipelines-operator/samples/dspa_simple.yaml
Labels: lgtm, approved

#766 Update model-mesh to v0.11.0-alpha
  model-mesh/base/params.env
  model-mesh/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  model-mesh/crd/bases/serving.kserve.io_servingruntimes.yaml
  model-mesh/default/config-defaults.yaml
  model-mesh/manager/kustomization.yaml
  model-mesh/manager/manager.yaml
Labels: lgtm

#767 Remove the creation of the anonymous namespace
  odh-common/base/kustomization.yaml
  odh-common/base/namespace.yaml
Labels: lgtm, approved

#734 Update for ODH Dashboard v2.8.0 release
  README.md
  odh-dashboard/OWNERS
  odh-dashboard/README.md
  odh-dashboard/base/deployment.yaml
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/base/model-serving-role-binding.yaml
  odh-dashboard/base/model-serving-role.yaml
  odh-dashboard/crd/kustomization.yaml
  odh-dashboard/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
  odh-dashboard/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  odh-dashboard/crd/odhdocuments.dashboard.opendatahub.io.crd.yaml
  odh-dashboard/crd/odhquickstarts.console.openshift.io.crd.yaml
  odh-dashboard/kfdef/README.md
  odh-dashboard/kfdef/odh-dashboard-kfnbc-test.yaml
  odh-dashboard/modelserving/kustomization.yaml
  odh-dashboard/modelserving/servingruntimes-config.yaml
  odh-dashboard/overlays/authentication/configmap.yaml
  odh-dashboard/overlays/authentication/kustomization.yaml
  odh-dashboard/overlays/odhdashboardconfig/kustomization.yaml
  odh-dashboard/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  odh-dashboard/overlays/odhdashboardconfig/odh-enabled-applications-config.configmap.yaml
  tests/Dockerfile
  tests/Makefile
  tests/basictests/dashboard.sh
  tests/resources/ods-ci/test-odh-dashboard-jupyterlab-notebook.robot
  tests/resources/ods-ci/test-variables.yml
Labels: lgtm, approved

#740 FAI-957: TrustyAI inclusion
  kfdef/trustyai.yaml
  model-mesh/default/config-defaults.yaml
  model-mesh/internal/base/deployment.yaml.tmpl
  tests/basictests/trustyai.sh
  tests/resources/trustyai/data.json
  tests/resources/trustyai/model.yaml
  tests/resources/trustyai/odh-mlserver-0.x.yaml
  tests/resources/trustyai/openvino-inference-service.yaml
  tests/resources/trustyai/sample-minio.yaml
  tests/resources/trustyai/secret.yaml
  tests/resources/trustyai/service_account.yaml
  tests/scripts/installandtest.sh
  tests/setup/odh-core.yaml
  trustyai-service/OWNERS
  trustyai-service/README.md
  trustyai-service/base/kustomization.yaml
  trustyai-service/base/pvc.yaml
  trustyai-service/base/route.yaml
  trustyai-service/base/trustyai-configmap.yaml
  trustyai-service/default/kustomization.yaml
  trustyai-service/default/trustyai-deployment.yaml
  trustyai-service/servicemonitors/kustomization.yaml
  trustyai-service/servicemonitors/trustyai-metrics.yaml
Labels: lgtm, approved, ok-to-test

#759 Update Notebook Controllers to v1.6.1
  odh-notebook-controller/gen_kubeflow_manifests.sh
  odh-notebook-controller/gen_odh_manifests.sh
  odh-notebook-controller/kf-notebook-controller/base/kustomization.yaml
  odh-notebook-controller/kf-notebook-controller/crd/bases/kubeflow.org_notebooks.yaml
  odh-notebook-controller/kf-notebook-controller/manager/manager.yaml
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/kustomization.yaml
  odh-notebook-controller/odh-notebook-controller/base/kustomization.yaml
  odh-notebook-controller/odh-notebook-controller/rbac/role.yaml
  tests/basictests/odh-notebook-controller.sh
Labels: lgtm, approved

#769 Up dspo memory to handle more users.
  data-science-pipelines-operator/manager/manager.yaml
Labels: lgtm, approved

#771 Update owners of dspo to match component repo.
  data-science-pipelines-operator/OWNERS
Labels: lgtm, approved
