Repository opendatahub-io/odh-manifests, pull requests merged in 2023-02, with the labels that each got.

#723 Add versions table
  README.md
Labels: lgtm, ok-to-test

#720 Add kube-linter command to makefile
  .aicoe-ci.yaml
  .kube-linter.yaml
  .thoth.yaml
  Makefile
Labels: lgtm, approved

#730 Update the CI test container to use chromium and chromedriver from epel repo
  tests/Dockerfile
Labels: lgtm, approved, ci/cd
