Repository opendatahub-io/odh-manifests, pull requests merged in 2023-08, with the labels that each got.

#893 Remove explainer configs and organize manifests
  kserve/base/inferenceservice-config-patch.yaml
  kserve/base/kustomization.yaml
  kserve/base/params.env
  kserve/base/user_cluster_roles.yaml
  kserve/hack/kustomization.yaml
  kserve/kserve-built/kserve-built.yaml
Labels: lgtm, approved

#900 Upgrade notebook-controller to v1.7.0-2 of odh/kubeflow
  odh-notebook-controller/gen_kubeflow_manifests.sh
  odh-notebook-controller/gen_odh_manifests.sh
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/kustomization.yaml
  odh-notebook-controller/odh-notebook-controller/base/kustomization.yaml
  tests/resources/ods-ci/test-odh-dashboard-jupyterlab-notebook.robot
Labels: lgtm, approved

#906 Add dspo v1.2.0
  data-science-pipelines-operator/base/params.env
  data-science-pipelines-operator/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Labels: lgtm, approved

#912 add odh-model-controller as an independent component
  odh-model-controller/base/kustomization.yaml
  odh-model-controller/base/params.env
  odh-model-controller/default/kustomization.yaml
  odh-model-controller/manager/controller_manager_config.yaml
  odh-model-controller/manager/kustomization.yaml
  odh-model-controller/manager/manager.yaml
  odh-model-controller/overlays/odh/kustomization.yaml
  odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
  odh-model-controller/overlays/odh/params.yaml
  odh-model-controller/prometheus/kustomization.yaml
  odh-model-controller/prometheus/monitor.yaml
  odh-model-controller/rbac/auth_proxy_client_clusterrole.yaml
  odh-model-controller/rbac/auth_proxy_role.yaml
  odh-model-controller/rbac/auth_proxy_role_binding.yaml
  odh-model-controller/rbac/auth_proxy_service.yaml
  odh-model-controller/rbac/kserve_prometheus_clusterrole.yaml
  odh-model-controller/rbac/kustomization.yaml
  odh-model-controller/rbac/leader_election_role.yaml
  odh-model-controller/rbac/leader_election_role_binding.yaml
  odh-model-controller/rbac/role.yaml
  odh-model-controller/rbac/role_binding.yaml
  odh-model-controller/rbac/service_account.yaml
Labels: lgtm, approved

#908 Upgrade to KServe v0.11
  kserve/base/inferenceservice-config-patch.yaml
  kserve/base/params.env
  kserve/hack/kustomization.yaml
  kserve/kserve-built/kserve-built.yaml
Labels: lgtm, approved

#917 2.14.1 Dashboard + Incubation
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/crd/acceleratorprofiles.opendatahub.io.crd.yaml
  odh-dashboard/crd/kustomization.yaml
  odh-dashboard/kfdef/README.md
Labels: approved

#918 Ensure odh-model-controller compatibility with kserve deployment mode
  model-mesh/odh-model-controller/crd/external/kustomization.yaml
  model-mesh/odh-model-controller/crd/external/security.istio.io_peerauthentications.yaml
  model-mesh/odh-model-controller/crd/external/telemetry.istio.io_telemetries.yaml
  model-mesh/odh-model-controller/default/kustomization.yaml
  model-mesh/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
  model-mesh/odh-model-controller/rbac/role.yaml
Labels: approved

#915 set annotations with recommended accelerators
  notebook-images/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  notebook-images/base/jupyter-pytorch-notebook-imagestream.yaml
  notebook-images/base/jupyter-tensorflow-notebook-imagestream.yaml
  notebook-images/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
Labels: lgtm, approved

#922 remove external istio crds from odh-model-controller manifests
  model-mesh/base/params.env
  model-mesh/odh-model-controller/crd/external/kustomization.yaml
  model-mesh/odh-model-controller/crd/external/security.istio.io_peerauthentications.yaml
  model-mesh/odh-model-controller/crd/external/telemetry.istio.io_telemetries.yaml
  model-mesh/odh-model-controller/default/kustomization.yaml
Labels: lgtm, approved

#921 Remove overriden field in KServe ConfigMap
  kserve/base/inferenceservice-config-patch.yaml
Labels: lgtm, approved

#925 Update DSP Operator manifests to v1.3.0
  data-science-pipelines-operator/base/params.env
Labels: lgtm, approved, ok-to-test
