Repository opendatahub-io/odh-manifests, pull requests merged in 2023-07, with the labels that each got.

#866 Fix rhods-9627
  model-mesh/base/kustomization.yaml
  model-mesh/odh-model-controller/overlays/odh/kustomization.yaml
  model-mesh/odh-modelmesh-controller/overlays/odh/kustomization.yaml
Labels: lgtm, approved

#854 Dashboard v2.12.0 release
  README.md
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/modelserving/ovms-gpu-ootb.yaml
  odh-dashboard/modelserving/ovms-ootb.yaml
Labels: lgtm, approved

#838 Add KServe manifests to odh-manifests
  kserve/OWNERS
  kserve/README.md
  kserve/base/inferenceservice-config-patch.yaml
  kserve/base/kserve-controller-manager-patch.yaml
  kserve/base/kustomization.yaml
  kserve/base/params.env
  kserve/base/params.yaml
  kserve/hack/build-kserve-manifests.sh
  kserve/hack/kustomization.yaml
  kserve/kserve-built/kserve-built.yaml
  kserve/kserve-built/kustomization.yaml
Labels: lgtm, approved, ok-to-test

#880 fix: rewrites url on notebook logout
  service-mesh/control-plane/base/resource-templates/08_virtual-service.yaml
Labels: lgtm, approved

#881 Fix modelmesh monitoring manifests
  modelmesh-monitoring/base/kustomization.yaml
  odh-dashboard/apps/jupyter/jupyter-app.yaml
  odh-dashboard/apps/jupyter/jupyterhub-app.yaml
Labels: lgtm

#887 create a clusterrole to allow normal users to create/delete the kserve CRs
  kserve/base/kustomization.yaml
  kserve/base/user_cluster_roles.yaml
Labels: lgtm, approved

#889 Fix software annotation to point the correct version on CUDA version (v1.7 branch)
  notebook-images/base/jupyter-pytorch-notebook-imagestream.yaml
Labels: lgtm, approved, ok-to-test

#879 Update dsp to v1.1.0
  data-science-pipelines-operator/base/params.env
  data-science-pipelines-operator/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  data-science-pipelines-operator/rbac/role.yaml
Labels: approved

#890 Fix env assignment with model mesh-monitoring manifests
  modelmesh-monitoring/base/kustomization.yaml
  modelmesh-monitoring/base/params.env
Labels: lgtm, approved

#888 Fix software annotation to point the correct version on CUDA version (master branch)
  notebook-images/base/jupyter-pytorch-notebook-imagestream.yaml
Labels: lgtm, approved, ok-to-test

#875 Sync odh-notebook-controller v1.7 manifests to odh-manifests
  odh-notebook-controller/gen_kubeflow_manifests.sh
  odh-notebook-controller/gen_odh_manifests.sh
  odh-notebook-controller/kf-notebook-controller/base/kustomization.yaml
  odh-notebook-controller/kf-notebook-controller/crd/patches/trivial_conversion_patch.yaml
  odh-notebook-controller/kf-notebook-controller/manager/kustomization.yaml
  odh-notebook-controller/kf-notebook-controller/manager/manager.yaml
  odh-notebook-controller/kf-notebook-controller/manager/params.env
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/kustomization.yaml
  odh-notebook-controller/kf-notebook-controller/overlays/openshift/manager_openshift_patch.yaml
  odh-notebook-controller/odh-notebook-controller/base/kustomization.yaml
Labels: lgtm, approved

#895 Update TrustyAI manifests to allow parameterized images
  trustyai-service-operator/base/kustomization.yaml
  trustyai-service-operator/base/params.env
  trustyai-service-operator/manager/kustomization.yaml
Labels: lgtm, approved
